Migrate the documentation to staging
pulp/pulp_container pull request #1528
Opened 2024-02-22 18:11 UTC by lubosmj

closes #1517

2024-02-22 18:15 UTC, lubosmj commented
![image](https://github.com/pulp/pulp_container/assets/8740962/4179c33e-4186-4cf4-82ae-0e1f5ae29b10)

2024-02-22 18:22 UTC, ipanova commented on staging_docs/admin/guides/change-allowed-artifacts.md
> +# Update Supported OCI Types
s/update/configure

2024-02-22 18:23 UTC, ipanova commented on staging_docs/admin/guides/migrate-permissions.md
> +# Migrate from Permissions
# Migrate from Permissions to Roles

2024-02-22 18:24 UTC, ipanova commented on staging_docs/admin/guides/sign-image.md
> +# Image Signing
Sign Images.
since you started with imperative format maybe continue with it

2024-02-22 18:26 UTC, ipanova commented
looks great!

2024-02-22 19:35 UTC, pedro-psb requested changes
Look great!
Apart from the user/tutorial which I commented in the Matrix, the other suggestions are just so you know you can, feel free to ignore.

2024-02-22 19:35 UTC, pedro-psb commented on staging_docs/user/tutorials/00-overview.md
You MAY put this on `user/index.md` to have it be displayed in the top-level of the plugin namespace, which is generally where overviews are.
I've just added this behavior pulp-docs, so feel free to leave it for later.

2024-02-22 19:35 UTC, pedro-psb commented on staging_docs/admin/learn/tech-preview.md
Would *may* put this in admin/reference, I've merged the changes that will correctly fetch them.

2024-02-24 12:21 UTC, lubosmj commented on staging_docs/user/tutorials/00-overview.md
I tried moving it to `user/index.md`. But, I cannot access this site from anywhere.

2024-02-24 12:30 UTC, lubosmj commented on staging_docs/admin/learn/tech-preview.md
I left it untouched. We already have such a structure in pulpcore. Will move it later.

2024-02-26 12:16 UTC, pedro-psb commented on staging_docs/user/tutorials/00-overview.md
I'll have a look on that later.

2024-02-26 12:17 UTC, pedro-psb approved these changes

2024-02-26 17:27 UTC, ipanova approved these changes

2024-02-26 17:27 UTC, merged